CREATE TABLE public.parcels
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    length integer,
    height integer,
    width integer
)

TABLESPACE pg_default;

ALTER TABLE public.parcels
    OWNER to postgres;

INSERT INTO parcels (length, height, width) VALUES
    (1,2,3),
    (1,2,3),
    (1,2,3),
    (1,2,3),
    (1,2,3),
    (1,2,3),
    (1,2,3),
    (1,2,3),
    (1,2,3),
    (1,2,3),
    (1,2,3),
    (1,2,3),
    (1,2,3),
    (1,2,3),
    (1,2,3);